name: multifilerag
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip=25.0
  - pandas>=1.5.0
  - numpy>=1.23.0
  - matplotlib>=3.6.0
  - seaborn>=0.12.0
  - pillow>=9.2.0
  - requests>=2.28.0
  - python-dotenv>=1.0.0
  - pip:
    - lightrag-hku[api]
    - "unstructured[all-docs]>=0.17.0"
    - PyPDF2>=3.0.0
    - fastapi>=0.104.0
    - uvicorn>=0.23.2
    - python-multipart>=0.0.6
    - pydantic>=2.4.2
    - httpx>=0.25.0
    - jinja2>=3.1.2
    - aiofiles>=23.2.1
